development:
  adapter: postgresql
  encoding: unicode
  database: fenix_dev
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: feniz_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: fenix_prod
  pool: 25
